### ISSUE TITLE
Supporting both PyQt4 and PyQt5

### ISSUE THREAD

**Issue by MatthieuDartiailh** [peterazmanov/enaml#22]
PyQt5 is not yet widely supported and will probably not be supported on Windows with Python 2. We could probably keep both versions running without too much trouble. Would you back a PR in that sense ?

**Comment by peterazmanov** [comment]
I think it's one of the easier parts, as we already have modules for supporting PySide and PyQt, the differences between PyQt4 and PyQt5 can be reflected there.

**Comment by MatthieuDartiailh** [comment]
Will be fixed in the original repo by https://github.com/nucleic/enaml/pull/228
